name: car_pool
description: A new Flutter project for sharing information regarding passengers pooling a vehicle to work

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.1.1

dependencies:
  flutter:
    sdk: flutter
  
  firebase_core: ^2.12.0
  firebase_auth: ^4.6.1
  http: ^0.13.4
  cloud_firestore: 4.17.5
  geolocator: ^13.0.0
  geocoding: ^2.0.0
  google_maps_flutter: ^2.0.0
  permission_handler: ^10.2.0
  flutter_local_notifications: ^17.0.0
  intl: ^0.18.0

  english_words: ^4.0.0
  provider: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true